name: Projeto J
favicon: null
layout_spectrum: 0.7208698824979365
typography_spectrum: 0.28345681563951075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c1e1f6'
    - '#3f84bb'
    - '#6ca2d0'
    - '#053162'
  brandStrength: 0.6875
  lightness: 0.5771380562800914
  saturation: 0.13103557052090764
  rhythmicContrast: 0.4213524784427136
purpose: []
